/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 7987f2038277defaae39921f81faa86c)
interface __BaseEnv_CloudflareEnv {
  NEXT_INC_CACHE_R2_BUCKET: R2Bucket
  IMAGES: ImagesBinding
  ASSETS: Fetcher
  NEXTJS_ENV: "production"
  NEXT_INC_CACHE_R2_PREFIX: "incremental-cache"
  WORKER_SELF_REFERENCE: Service<typeof import(".open-next/worker").default>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import(".open-next/worker")
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "NEXTJS_ENV" | "NEXT_INC_CACHE_R2_PREFIX">
  > {}
}
