import { defineConfig } from "oxfmt"

export default defineConfig({
  endOfLine: "lf",
  printWidth: 80,
  semi: false,
  singleQuote: false,
  sortImports: true,
  sortPackageJson: true,
  sortTailwindcss: {
    functions: ["cn", "cva", "clsx"],
    stylesheet: "packages/ui/src/styles/globals.css",
  },
  tabWidth: 2,
  trailingComma: "es5",
  ignorePatterns: [
    ".next/**",
    "**/.next/**",
    ".next-e2e/**",
    "**/.next-e2e/**",
    ".next-e2e-oauth/**",
    "**/.next-e2e-oauth/**",
    ".open-next/**",
    "**/.open-next/**",
    ".agents/skills/**",
    ".turbo/**",
    "**/.turbo/**",
    "**/*.md",
    "**/*.yml",
    "**/*.yaml",
    "coverage/**",
    "**/coverage/**",
    "dist/**",
    "**/dist/**",
    "node_modules/**",
    "**/node_modules/**",
    "storybook-static/**",
    "**/storybook-static/**",
    "test-results/**",
    "**/test-results/**",
    "playwright-report/**",
    "**/playwright-report/**",
    "**/next-env.d.ts",
  ],
})
