/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: eacfb7db75f7f6274615e47c14f6bdac)
interface __BaseEnv_CloudflareEnv {
  AGENT_RUNS_ENABLED: string
  AGENT_VISION_ENABLED: string
  AGENT_WRITES_ENABLED: string
  NODE_ENV: string
  SENTRY_ENVIRONMENT: string
  AGENT_INTERNAL_API: Service /* entrypoint AgentInternalApi from enterprise-agentic-saas-api */
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
    durableNamespaces: "IssueAssistant"
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AGENT_RUNS_ENABLED"
      | "AGENT_VISION_ENABLED"
      | "AGENT_WRITES_ENABLED"
      | "NODE_ENV"
      | "SENTRY_ENVIRONMENT"
    >
  > {}
}
