/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: 735952495c6587473bd4a4706e023628)
interface __BaseEnv_CloudflareEnv {
  AGENT_RUNS_ENABLED: string
  AGENT_VISION_ENABLED: string
  AGENT_WRITES_ENABLED: string
  MASTRA_STORAGE_URL: string
  NODE_ENV: string
  AGENT_INTERNAL_API: Service /* entrypoint AgentInternalApi from enterprise-agentic-saas-api */
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./mastra/worker")
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AGENT_RUNS_ENABLED"
      | "AGENT_VISION_ENABLED"
      | "AGENT_WRITES_ENABLED"
      | "MASTRA_STORAGE_URL"
      | "NODE_ENV"
    >
  > {}
}
