/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: c8bf4253aa291ac0c942a39b6ddbe9f7)
interface __BaseEnv_CloudflareEnv {
  WEB_ORIGIN: string
  IssueAssistant: DurableObjectNamespace<import("./worker").IssueAssistant>
  AGENT_INTERNAL_API: Service /* entrypoint AgentInternalApi from enterprise-agentic-saas-api */
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
    durableNamespaces: "IssueAssistant"
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "WEB_ORIGIN">
  > {}
}
