/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: f84064260b0305b611ad97ef2ff340db)
interface __BaseEnv_CloudflareEnv {
  FILES: R2Bucket
  IMAGES: ImagesBinding
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
