/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteRouteImport } from './routes/_console/route'
import { Route as publicDocsRouteRouteImport } from './routes/(public)/docs/route'
import { Route as publicDocsDotmdRouteImport } from './routes/(public)/docs[.]md'
import { Route as publicLlmsFullDottxtRouteImport } from './routes/(public)/llms-full[.]txt'
import { Route as publicLlmsDottxtRouteImport } from './routes/(public)/llms[.]txt'
import { Route as ConsoleOnboardingRouteImport } from './routes/_console/onboarding'
import { Route as publicApiSearchRouteImport } from './routes/(public)/api/search'
import { Route as publicAuthPathRouteImport } from './routes/(public)/auth/$path'
import { Route as publicDocsIndexRouteImport } from './routes/(public)/docs/index'
import { Route as publicDocsSplatRouteImport } from './routes/(public)/docs/$'
import { Route as publicDocsChar123Char125DotmdRouteImport } from './routes/(public)/docs/{$}[.]md'
import { Route as publicInvitationsInvitationIdRouteImport } from './routes/(public)/invitations/$invitationId'
import { Route as publicOauthConsentRouteImport } from './routes/(public)/oauth/consent'
import { Route as publicOauthOrganizationRouteImport } from './routes/(public)/oauth/organization'
import { Route as ConsoleDashboardIndexRouteImport } from './routes/_console/dashboard/index'
import { Route as ConsoleDashboardTodosRouteImport } from './routes/_console/dashboard/todos'
import { Route as ConsoleSettingsAccountRouteImport } from './routes/_console/settings/account'
import { Route as ConsoleSettingsOrganizationsRouteImport } from './routes/_console/settings/organizations'
import { Route as ConsoleSettingsProfileRouteImport } from './routes/_console/settings/profile'
import { Route as ConsoleSettingsSessionsRouteImport } from './routes/_console/settings/sessions'
import { Route as publicOrganizationInvitationsInvitationIdRouteImport } from './routes/(public)/organization/invitations/$invitationId'
import { Route as ConsoleOrganizationOrganizationSlugDashboardRouteImport } from './routes/_console/organization/$organizationSlug/dashboard'
import { Route as ConsoleOrganizationOrganizationSlugMembersRouteImport } from './routes/_console/organization/$organizationSlug/members'
import { Route as ConsoleOrganizationOrganizationSlugSettingsRouteImport } from './routes/_console/organization/$organizationSlug/settings'
import { Route as ConsoleOrganizationOrganizationSlugIssuesIndexRouteImport } from './routes/_console/organization/$organizationSlug/issues/index'
import { Route as ConsoleOrganizationOrganizationSlugIssuesIssueNumberRouteImport } from './routes/_console/organization/$organizationSlug/issues/$issueNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsRouteRoute = publicDocsRouteRouteImport.update({
  id: '/(public)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsDotmdRoute = publicDocsDotmdRouteImport.update({
  id: '/(public)/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLlmsFullDottxtRoute = publicLlmsFullDottxtRouteImport.update({
  id: '/(public)/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLlmsDottxtRoute = publicLlmsDottxtRouteImport.update({
  id: '/(public)/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleOnboardingRoute = ConsoleOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const publicApiSearchRoute = publicApiSearchRouteImport.update({
  id: '/(public)/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthPathRoute = publicAuthPathRouteImport.update({
  id: '/(public)/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsIndexRoute = publicDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicDocsRouteRoute,
} as any)
const publicDocsSplatRoute = publicDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => publicDocsRouteRoute,
} as any)
const publicDocsChar123Char125DotmdRoute =
  publicDocsChar123Char125DotmdRouteImport.update({
    id: '/{$}.md',
    path: '/{$}.md',
    getParentRoute: () => publicDocsRouteRoute,
  } as any)
const publicInvitationsInvitationIdRoute =
  publicInvitationsInvitationIdRouteImport.update({
    id: '/(public)/invitations/$invitationId',
    path: '/invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicOauthConsentRoute = publicOauthConsentRouteImport.update({
  id: '/(public)/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOauthOrganizationRoute = publicOauthOrganizationRouteImport.update({
  id: '/(public)/oauth/organization',
  path: '/oauth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleDashboardIndexRoute = ConsoleDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleDashboardTodosRoute = ConsoleDashboardTodosRouteImport.update({
  id: '/dashboard/todos',
  path: '/dashboard/todos',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsAccountRoute = ConsoleSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsOrganizationsRoute =
  ConsoleSettingsOrganizationsRouteImport.update({
    id: '/settings/organizations',
    path: '/settings/organizations',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleSettingsProfileRoute = ConsoleSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsSessionsRoute = ConsoleSettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const publicOrganizationInvitationsInvitationIdRoute =
  publicOrganizationInvitationsInvitationIdRouteImport.update({
    id: '/(public)/organization/invitations/$invitationId',
    path: '/organization/invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsoleOrganizationOrganizationSlugDashboardRoute =
  ConsoleOrganizationOrganizationSlugDashboardRouteImport.update({
    id: '/organization/$organizationSlug/dashboard',
    path: '/organization/$organizationSlug/dashboard',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleOrganizationOrganizationSlugMembersRoute =
  ConsoleOrganizationOrganizationSlugMembersRouteImport.update({
    id: '/organization/$organizationSlug/members',
    path: '/organization/$organizationSlug/members',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleOrganizationOrganizationSlugSettingsRoute =
  ConsoleOrganizationOrganizationSlugSettingsRouteImport.update({
    id: '/organization/$organizationSlug/settings',
    path: '/organization/$organizationSlug/settings',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleOrganizationOrganizationSlugIssuesIndexRoute =
  ConsoleOrganizationOrganizationSlugIssuesIndexRouteImport.update({
    id: '/organization/$organizationSlug/issues/',
    path: '/organization/$organizationSlug/issues/',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute =
  ConsoleOrganizationOrganizationSlugIssuesIssueNumberRouteImport.update({
    id: '/organization/$organizationSlug/issues/$issueNumber',
    path: '/organization/$organizationSlug/issues/$issueNumber',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof publicDocsRouteRouteWithChildren
  '/docs.md': typeof publicDocsDotmdRoute
  '/llms-full.txt': typeof publicLlmsFullDottxtRoute
  '/llms.txt': typeof publicLlmsDottxtRoute
  '/onboarding': typeof ConsoleOnboardingRoute
  '/api/search': typeof publicApiSearchRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/docs/$': typeof publicDocsSplatRoute
  '/docs/{$}.md': typeof publicDocsChar123Char125DotmdRoute
  '/invitations/$invitationId': typeof publicInvitationsInvitationIdRoute
  '/oauth/consent': typeof publicOauthConsentRoute
  '/oauth/organization': typeof publicOauthOrganizationRoute
  '/dashboard/todos': typeof ConsoleDashboardTodosRoute
  '/settings/account': typeof ConsoleSettingsAccountRoute
  '/settings/organizations': typeof ConsoleSettingsOrganizationsRoute
  '/settings/profile': typeof ConsoleSettingsProfileRoute
  '/settings/sessions': typeof ConsoleSettingsSessionsRoute
  '/docs/': typeof publicDocsIndexRoute
  '/dashboard/': typeof ConsoleDashboardIndexRoute
  '/organization/invitations/$invitationId': typeof publicOrganizationInvitationsInvitationIdRoute
  '/organization/$organizationSlug/dashboard': typeof ConsoleOrganizationOrganizationSlugDashboardRoute
  '/organization/$organizationSlug/members': typeof ConsoleOrganizationOrganizationSlugMembersRoute
  '/organization/$organizationSlug/settings': typeof ConsoleOrganizationOrganizationSlugSettingsRoute
  '/organization/$organizationSlug/issues/$issueNumber': typeof ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute
  '/organization/$organizationSlug/issues/': typeof ConsoleOrganizationOrganizationSlugIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs.md': typeof publicDocsDotmdRoute
  '/llms-full.txt': typeof publicLlmsFullDottxtRoute
  '/llms.txt': typeof publicLlmsDottxtRoute
  '/onboarding': typeof ConsoleOnboardingRoute
  '/api/search': typeof publicApiSearchRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/docs/$': typeof publicDocsSplatRoute
  '/docs/{$}.md': typeof publicDocsChar123Char125DotmdRoute
  '/invitations/$invitationId': typeof publicInvitationsInvitationIdRoute
  '/oauth/consent': typeof publicOauthConsentRoute
  '/oauth/organization': typeof publicOauthOrganizationRoute
  '/dashboard/todos': typeof ConsoleDashboardTodosRoute
  '/settings/account': typeof ConsoleSettingsAccountRoute
  '/settings/organizations': typeof ConsoleSettingsOrganizationsRoute
  '/settings/profile': typeof ConsoleSettingsProfileRoute
  '/settings/sessions': typeof ConsoleSettingsSessionsRoute
  '/docs': typeof publicDocsIndexRoute
  '/dashboard': typeof ConsoleDashboardIndexRoute
  '/organization/invitations/$invitationId': typeof publicOrganizationInvitationsInvitationIdRoute
  '/organization/$organizationSlug/dashboard': typeof ConsoleOrganizationOrganizationSlugDashboardRoute
  '/organization/$organizationSlug/members': typeof ConsoleOrganizationOrganizationSlugMembersRoute
  '/organization/$organizationSlug/settings': typeof ConsoleOrganizationOrganizationSlugSettingsRoute
  '/organization/$organizationSlug/issues/$issueNumber': typeof ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute
  '/organization/$organizationSlug/issues': typeof ConsoleOrganizationOrganizationSlugIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteRouteWithChildren
  '/(public)/docs': typeof publicDocsRouteRouteWithChildren
  '/(public)/docs.md': typeof publicDocsDotmdRoute
  '/(public)/llms-full.txt': typeof publicLlmsFullDottxtRoute
  '/(public)/llms.txt': typeof publicLlmsDottxtRoute
  '/_console/onboarding': typeof ConsoleOnboardingRoute
  '/(public)/api/search': typeof publicApiSearchRoute
  '/(public)/auth/$path': typeof publicAuthPathRoute
  '/(public)/docs/$': typeof publicDocsSplatRoute
  '/(public)/docs/{$}.md': typeof publicDocsChar123Char125DotmdRoute
  '/(public)/invitations/$invitationId': typeof publicInvitationsInvitationIdRoute
  '/(public)/oauth/consent': typeof publicOauthConsentRoute
  '/(public)/oauth/organization': typeof publicOauthOrganizationRoute
  '/_console/dashboard/todos': typeof ConsoleDashboardTodosRoute
  '/_console/settings/account': typeof ConsoleSettingsAccountRoute
  '/_console/settings/organizations': typeof ConsoleSettingsOrganizationsRoute
  '/_console/settings/profile': typeof ConsoleSettingsProfileRoute
  '/_console/settings/sessions': typeof ConsoleSettingsSessionsRoute
  '/(public)/docs/': typeof publicDocsIndexRoute
  '/_console/dashboard/': typeof ConsoleDashboardIndexRoute
  '/(public)/organization/invitations/$invitationId': typeof publicOrganizationInvitationsInvitationIdRoute
  '/_console/organization/$organizationSlug/dashboard': typeof ConsoleOrganizationOrganizationSlugDashboardRoute
  '/_console/organization/$organizationSlug/members': typeof ConsoleOrganizationOrganizationSlugMembersRoute
  '/_console/organization/$organizationSlug/settings': typeof ConsoleOrganizationOrganizationSlugSettingsRoute
  '/_console/organization/$organizationSlug/issues/$issueNumber': typeof ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute
  '/_console/organization/$organizationSlug/issues/': typeof ConsoleOrganizationOrganizationSlugIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/onboarding'
    | '/api/search'
    | '/auth/$path'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/invitations/$invitationId'
    | '/oauth/consent'
    | '/oauth/organization'
    | '/dashboard/todos'
    | '/settings/account'
    | '/settings/organizations'
    | '/settings/profile'
    | '/settings/sessions'
    | '/docs/'
    | '/dashboard/'
    | '/organization/invitations/$invitationId'
    | '/organization/$organizationSlug/dashboard'
    | '/organization/$organizationSlug/members'
    | '/organization/$organizationSlug/settings'
    | '/organization/$organizationSlug/issues/$issueNumber'
    | '/organization/$organizationSlug/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/onboarding'
    | '/api/search'
    | '/auth/$path'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/invitations/$invitationId'
    | '/oauth/consent'
    | '/oauth/organization'
    | '/dashboard/todos'
    | '/settings/account'
    | '/settings/organizations'
    | '/settings/profile'
    | '/settings/sessions'
    | '/docs'
    | '/dashboard'
    | '/organization/invitations/$invitationId'
    | '/organization/$organizationSlug/dashboard'
    | '/organization/$organizationSlug/members'
    | '/organization/$organizationSlug/settings'
    | '/organization/$organizationSlug/issues/$issueNumber'
    | '/organization/$organizationSlug/issues'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/(public)/docs'
    | '/(public)/docs.md'
    | '/(public)/llms-full.txt'
    | '/(public)/llms.txt'
    | '/_console/onboarding'
    | '/(public)/api/search'
    | '/(public)/auth/$path'
    | '/(public)/docs/$'
    | '/(public)/docs/{$}.md'
    | '/(public)/invitations/$invitationId'
    | '/(public)/oauth/consent'
    | '/(public)/oauth/organization'
    | '/_console/dashboard/todos'
    | '/_console/settings/account'
    | '/_console/settings/organizations'
    | '/_console/settings/profile'
    | '/_console/settings/sessions'
    | '/(public)/docs/'
    | '/_console/dashboard/'
    | '/(public)/organization/invitations/$invitationId'
    | '/_console/organization/$organizationSlug/dashboard'
    | '/_console/organization/$organizationSlug/members'
    | '/_console/organization/$organizationSlug/settings'
    | '/_console/organization/$organizationSlug/issues/$issueNumber'
    | '/_console/organization/$organizationSlug/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  publicDocsRouteRoute: typeof publicDocsRouteRouteWithChildren
  publicDocsDotmdRoute: typeof publicDocsDotmdRoute
  publicLlmsFullDottxtRoute: typeof publicLlmsFullDottxtRoute
  publicLlmsDottxtRoute: typeof publicLlmsDottxtRoute
  publicApiSearchRoute: typeof publicApiSearchRoute
  publicAuthPathRoute: typeof publicAuthPathRoute
  publicInvitationsInvitationIdRoute: typeof publicInvitationsInvitationIdRoute
  publicOauthConsentRoute: typeof publicOauthConsentRoute
  publicOauthOrganizationRoute: typeof publicOauthOrganizationRoute
  publicOrganizationInvitationsInvitationIdRoute: typeof publicOrganizationInvitationsInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs': {
      id: '/(public)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof publicDocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs.md': {
      id: '/(public)/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof publicDocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/llms-full.txt': {
      id: '/(public)/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof publicLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/llms.txt': {
      id: '/(public)/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof publicLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/onboarding': {
      id: '/_console/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ConsoleOnboardingRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/(public)/api/search': {
      id: '/(public)/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof publicApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/$path': {
      id: '/(public)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof publicAuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs/': {
      id: '/(public)/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof publicDocsIndexRouteImport
      parentRoute: typeof publicDocsRouteRoute
    }
    '/(public)/docs/$': {
      id: '/(public)/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof publicDocsSplatRouteImport
      parentRoute: typeof publicDocsRouteRoute
    }
    '/(public)/docs/{$}.md': {
      id: '/(public)/docs/{$}.md'
      path: '/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof publicDocsChar123Char125DotmdRouteImport
      parentRoute: typeof publicDocsRouteRoute
    }
    '/(public)/invitations/$invitationId': {
      id: '/(public)/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof publicInvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/oauth/consent': {
      id: '/(public)/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof publicOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/oauth/organization': {
      id: '/(public)/oauth/organization'
      path: '/oauth/organization'
      fullPath: '/oauth/organization'
      preLoaderRoute: typeof publicOauthOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/dashboard/': {
      id: '/_console/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ConsoleDashboardIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/dashboard/todos': {
      id: '/_console/dashboard/todos'
      path: '/dashboard/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof ConsoleDashboardTodosRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/account': {
      id: '/_console/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ConsoleSettingsAccountRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/organizations': {
      id: '/_console/settings/organizations'
      path: '/settings/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof ConsoleSettingsOrganizationsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/profile': {
      id: '/_console/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ConsoleSettingsProfileRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/sessions': {
      id: '/_console/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof ConsoleSettingsSessionsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/(public)/organization/invitations/$invitationId': {
      id: '/(public)/organization/invitations/$invitationId'
      path: '/organization/invitations/$invitationId'
      fullPath: '/organization/invitations/$invitationId'
      preLoaderRoute: typeof publicOrganizationInvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/organization/$organizationSlug/dashboard': {
      id: '/_console/organization/$organizationSlug/dashboard'
      path: '/organization/$organizationSlug/dashboard'
      fullPath: '/organization/$organizationSlug/dashboard'
      preLoaderRoute: typeof ConsoleOrganizationOrganizationSlugDashboardRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/organization/$organizationSlug/members': {
      id: '/_console/organization/$organizationSlug/members'
      path: '/organization/$organizationSlug/members'
      fullPath: '/organization/$organizationSlug/members'
      preLoaderRoute: typeof ConsoleOrganizationOrganizationSlugMembersRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/organization/$organizationSlug/settings': {
      id: '/_console/organization/$organizationSlug/settings'
      path: '/organization/$organizationSlug/settings'
      fullPath: '/organization/$organizationSlug/settings'
      preLoaderRoute: typeof ConsoleOrganizationOrganizationSlugSettingsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/organization/$organizationSlug/issues/': {
      id: '/_console/organization/$organizationSlug/issues/'
      path: '/organization/$organizationSlug/issues'
      fullPath: '/organization/$organizationSlug/issues/'
      preLoaderRoute: typeof ConsoleOrganizationOrganizationSlugIssuesIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/organization/$organizationSlug/issues/$issueNumber': {
      id: '/_console/organization/$organizationSlug/issues/$issueNumber'
      path: '/organization/$organizationSlug/issues/$issueNumber'
      fullPath: '/organization/$organizationSlug/issues/$issueNumber'
      preLoaderRoute: typeof ConsoleOrganizationOrganizationSlugIssuesIssueNumberRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleOnboardingRoute: typeof ConsoleOnboardingRoute
  ConsoleDashboardTodosRoute: typeof ConsoleDashboardTodosRoute
  ConsoleSettingsAccountRoute: typeof ConsoleSettingsAccountRoute
  ConsoleSettingsOrganizationsRoute: typeof ConsoleSettingsOrganizationsRoute
  ConsoleSettingsProfileRoute: typeof ConsoleSettingsProfileRoute
  ConsoleSettingsSessionsRoute: typeof ConsoleSettingsSessionsRoute
  ConsoleDashboardIndexRoute: typeof ConsoleDashboardIndexRoute
  ConsoleOrganizationOrganizationSlugDashboardRoute: typeof ConsoleOrganizationOrganizationSlugDashboardRoute
  ConsoleOrganizationOrganizationSlugMembersRoute: typeof ConsoleOrganizationOrganizationSlugMembersRoute
  ConsoleOrganizationOrganizationSlugSettingsRoute: typeof ConsoleOrganizationOrganizationSlugSettingsRoute
  ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute: typeof ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute
  ConsoleOrganizationOrganizationSlugIssuesIndexRoute: typeof ConsoleOrganizationOrganizationSlugIssuesIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleOnboardingRoute: ConsoleOnboardingRoute,
  ConsoleDashboardTodosRoute: ConsoleDashboardTodosRoute,
  ConsoleSettingsAccountRoute: ConsoleSettingsAccountRoute,
  ConsoleSettingsOrganizationsRoute: ConsoleSettingsOrganizationsRoute,
  ConsoleSettingsProfileRoute: ConsoleSettingsProfileRoute,
  ConsoleSettingsSessionsRoute: ConsoleSettingsSessionsRoute,
  ConsoleDashboardIndexRoute: ConsoleDashboardIndexRoute,
  ConsoleOrganizationOrganizationSlugDashboardRoute:
    ConsoleOrganizationOrganizationSlugDashboardRoute,
  ConsoleOrganizationOrganizationSlugMembersRoute:
    ConsoleOrganizationOrganizationSlugMembersRoute,
  ConsoleOrganizationOrganizationSlugSettingsRoute:
    ConsoleOrganizationOrganizationSlugSettingsRoute,
  ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute:
    ConsoleOrganizationOrganizationSlugIssuesIssueNumberRoute,
  ConsoleOrganizationOrganizationSlugIssuesIndexRoute:
    ConsoleOrganizationOrganizationSlugIssuesIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

interface publicDocsRouteRouteChildren {
  publicDocsSplatRoute: typeof publicDocsSplatRoute
  publicDocsChar123Char125DotmdRoute: typeof publicDocsChar123Char125DotmdRoute
  publicDocsIndexRoute: typeof publicDocsIndexRoute
}

const publicDocsRouteRouteChildren: publicDocsRouteRouteChildren = {
  publicDocsSplatRoute: publicDocsSplatRoute,
  publicDocsChar123Char125DotmdRoute: publicDocsChar123Char125DotmdRoute,
  publicDocsIndexRoute: publicDocsIndexRoute,
}

const publicDocsRouteRouteWithChildren = publicDocsRouteRoute._addFileChildren(
  publicDocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  publicDocsRouteRoute: publicDocsRouteRouteWithChildren,
  publicDocsDotmdRoute: publicDocsDotmdRoute,
  publicLlmsFullDottxtRoute: publicLlmsFullDottxtRoute,
  publicLlmsDottxtRoute: publicLlmsDottxtRoute,
  publicApiSearchRoute: publicApiSearchRoute,
  publicAuthPathRoute: publicAuthPathRoute,
  publicInvitationsInvitationIdRoute: publicInvitationsInvitationIdRoute,
  publicOauthConsentRoute: publicOauthConsentRoute,
  publicOauthOrganizationRoute: publicOauthOrganizationRoute,
  publicOrganizationInvitationsInvitationIdRoute:
    publicOrganizationInvitationsInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
