/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: 1096363ae3460fd5ed298dfaf2cb52d3)
interface __BaseEnv_CloudflareEnv {
  FILES: R2Bucket
  EMAIL: SendEmail
  IMAGES: ImagesBinding
  NODE_ENV: string
  APP_NAME: string
  APP_BASE_URL: string
  API_PUBLIC_URL: string
  AGENT_ASSET_UPLOAD_ENABLED: string
  BETTER_AUTH_URL: string
  BETTER_AUTH_SECRET: string
  AUTH_COOKIE_DOMAIN: string
  TRUSTED_ORIGINS: string
  CORS_ORIGIN: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  TURSO_DATABASE_URL: string
  TURSO_AUTH_TOKEN: string
  EMAIL_PROVIDER: string
  EMAIL_FROM: string
  IMAGE_PREVIEWS: Fetcher /* enterprise-agentic-saas-images */
  AGENT_RUNTIME: Service /* entrypoint AgentRuntime from enterprise-agentic-saas-agent */
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "NODE_ENV"
      | "APP_NAME"
      | "APP_BASE_URL"
      | "API_PUBLIC_URL"
      | "AGENT_ASSET_UPLOAD_ENABLED"
      | "BETTER_AUTH_URL"
      | "BETTER_AUTH_SECRET"
      | "AUTH_COOKIE_DOMAIN"
      | "TRUSTED_ORIGINS"
      | "CORS_ORIGIN"
      | "GITHUB_CLIENT_ID"
      | "GITHUB_CLIENT_SECRET"
      | "TURSO_DATABASE_URL"
      | "TURSO_AUTH_TOKEN"
      | "EMAIL_PROVIDER"
      | "EMAIL_FROM"
    >
  > {}
}
