import { defineRelations } from "drizzle-orm"

import {
  agentActionAssets,
  agentActions,
  agentApprovalPolicies,
  agentAssets,
  agentConnectionTickets,
  agentGrants,
  agentModelPrices,
  agentResourceUsageBuckets,
  agentResourceUsageOperations,
  agentResumeTickets,
  agentRunAssets,
  agentRuns,
  agentSessionContexts,
  agentThreadPermissions,
  agentThreads,
  agentUsageDaily,
  agentUsageEvents,
  auditLogs,
  fileCleanupJobs,
  files,
  issueActivityEvents,
  issueComments,
  issueFileOwners,
  issues,
  issueThumbnailSelections,
  mcpAttachmentUploads,
  mcpToolOperations,
  organizationDeletionJobs,
  organizationFileUsage,
  profileImageCleanupJobs,
  profileImages,
  storageObjectClaims,
  storageObjectCleanupJobs,
  storageObjects,
} from "./app"
import {
  account,
  authRelations,
  invitation,
  member,
  organization,
  passkey,
  rateLimit,
  session,
  user,
  verification,
} from "./auth.generated"
import {
  oauthAccessToken,
  oauthClient,
  oauthClientAssertion,
  oauthClientResource,
  oauthConsent,
  oauthProviderRelations,
  oauthRefreshToken,
  oauthResource,
} from "./oauth-provider"

const baseRelations = defineRelations({
  account,
  agentActionAssets,
  agentActions,
  agentApprovalPolicies,
  agentAssets,
  agentConnectionTickets,
  agentGrants,
  agentModelPrices,
  agentResourceUsageBuckets,
  agentResourceUsageOperations,
  agentResumeTickets,
  agentRunAssets,
  agentRuns,
  agentSessionContexts,
  agentThreadPermissions,
  agentThreads,
  agentUsageDaily,
  agentUsageEvents,
  auditLogs,
  fileCleanupJobs,
  files,
  invitation,
  issueActivityEvents,
  issueComments,
  issueFileOwners,
  issues,
  issueThumbnailSelections,
  mcpAttachmentUploads,
  mcpToolOperations,
  member,
  oauthAccessToken,
  oauthClient,
  oauthClientAssertion,
  oauthClientResource,
  oauthConsent,
  oauthRefreshToken,
  oauthResource,
  organization,
  organizationDeletionJobs,
  organizationFileUsage,
  passkey,
  profileImageCleanupJobs,
  profileImages,
  rateLimit,
  session,
  storageObjectClaims,
  storageObjectCleanupJobs,
  storageObjects,
  user,
  verification,
})

export const relations = {
  ...baseRelations,
  ...authRelations,
  ...oauthProviderRelations,
  user: {
    ...authRelations.user,
    relations: {
      ...authRelations.user.relations,
      ...oauthProviderRelations.user.relations,
    },
  },
  session: {
    ...authRelations.session,
    relations: {
      ...authRelations.session.relations,
      ...oauthProviderRelations.session.relations,
    },
  },
}
