export const clientEnv = {
  NEXT_PUBLIC_BROWSER_TEST: process.env.NEXT_PUBLIC_BROWSER_TEST,
  NEXT_PUBLIC_API_BASE_URL:
    process.env.NEXT_PUBLIC_API_BASE_URL ??
    "https://api.enterprise-agentic-saas.localhost",
  NEXT_PUBLIC_DEV_SESSION_ID: process.env.NEXT_PUBLIC_DEV_SESSION_ID,
  NEXT_PUBLIC_DEV_WORKTREE_ID: process.env.NEXT_PUBLIC_DEV_WORKTREE_ID,
  NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT:
    process.env.NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT,
}
